# Generated by Django 4.2 on 2025-07-15 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم القسم"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="وصف القسم"),
                ),
            ],
            options={
                "verbose_name": "قسم",
                "verbose_name_plural": "الأقسام",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "توزيع",
                "verbose_name_plural": "التوزيعات",
                "ordering": ["fk_group__group_name", "fk_subject__subject_name"],
            },
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hall_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="اسم القاعة"
                    ),
                ),
                (
                    "capacity_hall",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="سعة القاعة",
                    ),
                ),
                (
                    "hall_status",
                    models.CharField(
                        choices=[("متاحة", "متاحة"), ("تحت الصيانة", "تحت الصيانة")],
                        default="متاحة",
                        max_length=20,
                        verbose_name="حالة القاعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "قاعة",
                "verbose_name_plural": "القاعات",
                "ordering": ["-capacity_hall"],
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_from",
                    models.CharField(
                        help_text="مثال: 08:00", max_length=10, verbose_name="من الساعة"
                    ),
                ),
                (
                    "period_to",
                    models.CharField(
                        help_text="مثال: 10:00",
                        max_length=10,
                        verbose_name="إلى الساعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "فترة",
                "verbose_name_plural": "الفترات",
                "unique_together": {("period_from", "period_to")},
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "subject_name",
                    models.CharField(max_length=100, verbose_name="اسم المادة"),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[("الأول", "الأول"), ("الثاني", "الثاني")],
                        default="الأول",
                        max_length=10,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
            ],
            options={
                "verbose_name": "مادة",
                "verbose_name_plural": "المواد",
                "ordering": ["subject_name"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
                ),
                (
                    "table",
                    models.FileField(
                        upload_to="tables_file/", verbose_name="ملف الجدول"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الجدول"
                    ),
                ),
            ],
            options={
                "verbose_name": "جدول",
                "verbose_name_plural": "الجداول",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "teacher_name",
                    models.CharField(max_length=50, verbose_name="اسم المدرس"),
                ),
                (
                    "teacher_address",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="عنوان المدرس",
                    ),
                ),
                (
                    "teacher_phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="هاتف المدرس"
                    ),
                ),
                (
                    "teacher_email",
                    models.EmailField(
                        max_length=100,
                        unique=True,
                        verbose_name="بريد المدرس الإلكتروني",
                    ),
                ),
                (
                    "teacher_status",
                    models.CharField(
                        choices=[("نشط", "نشط"), ("إجازة", "إجازة")],
                        default="نشط",
                        max_length=100,
                        verbose_name="حالة المدرس",
                    ),
                ),
            ],
            options={
                "verbose_name": "المدرس",
                "verbose_name_plural": "المدرسين",
                "ordering": ["teacher_name"],
            },
        ),
        migrations.CreateModel(
            name="Today",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("day_name", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "verbose_name": "يوم",
                "verbose_name_plural": "الأيام",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program_name",
                    models.CharField(max_length=50, verbose_name="اسم البرنامج"),
                ),
                (
                    "fk_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="timetable.department",
                        verbose_name="القسم التابع له",
                    ),
                ),
            ],
            options={
                "verbose_name": "برنامج",
                "verbose_name_plural": "البرامج",
                "ordering": ["program_name"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_name",
                    models.CharField(
                        choices=[
                            ("الأول", "الأول"),
                            ("الثاني", "الثاني"),
                            ("الثالث", "الثالث"),
                            ("الرابع", "الرابع"),
                        ],
                        max_length=50,
                        verbose_name="اسم المستوى",
                    ),
                ),
                (
                    "number_students",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="عدد الطلاب",
                    ),
                ),
                (
                    "fk_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="timetable.program",
                        verbose_name="البرنامج",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستوى",
                "verbose_name_plural": "المستويات",
                "unique_together": {("level_name", "fk_program")},
            },
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_day",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_lectures",
                        to="timetable.today",
                        verbose_name="اليوم",
                    ),
                ),
                (
                    "fk_distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to="timetable.distribution",
                        verbose_name="التوزيع",
                    ),
                ),
                (
                    "fk_hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to="timetable.hall",
                        verbose_name="القاعة",
                    ),
                ),
                (
                    "fk_period",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_lectures",
                        to="timetable.period",
                        verbose_name="الفترة",
                    ),
                ),
                (
                    "fk_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to="timetable.table",
                        verbose_name="الجدول",
                    ),
                ),
            ],
            options={
                "verbose_name": "محاضرة",
                "verbose_name_plural": "المحاضرات",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(max_length=50, verbose_name="اسم المجموعة"),
                ),
                (
                    "number_students",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="عدد الطلاب",
                    ),
                ),
                (
                    "fk_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="timetable.level",
                        verbose_name="المستوى",
                    ),
                ),
            ],
            options={
                "verbose_name": "مجموعة",
                "verbose_name_plural": "المجموعات",
                "ordering": ["fk_level__level_name", "group_name"],
                "unique_together": {("group_name", "fk_level")},
            },
        ),
        migrations.AddField(
            model_name="distribution",
            name="fk_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distributions",
                to="timetable.group",
                verbose_name="المجموعة",
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="fk_subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distributions",
                to="timetable.subject",
                verbose_name="المادة",
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="fk_teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distributions",
                to="timetable.teacher",
                verbose_name="الأستاذ",
            ),
        ),
        migrations.CreateModel(
            name="TeacherTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_availability",
                        to="timetable.period",
                        verbose_name="الفترة",
                    ),
                ),
                (
                    "fk_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available_times",
                        to="timetable.teacher",
                        verbose_name="الأستاذ",
                    ),
                ),
                (
                    "fk_today",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_availability",
                        to="timetable.today",
                        verbose_name="اليوم",
                    ),
                ),
            ],
            options={
                "verbose_name": "وقت الأستاذ",
                "verbose_name_plural": "أوقات الأساتذة",
                "ordering": [
                    "fk_teacher__teacher_name",
                    "fk_today__id",
                    "fk_period__period_from",
                ],
                "unique_together": {("fk_teacher", "fk_today", "fk_period")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="distribution",
            unique_together={("fk_group", "fk_teacher", "fk_subject")},
        ),
    ]
