# Generated by Django 5.2.3 on 2025-06-24 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hall_name",
                    models.CharField(max_length=50, verbose_name="اسم القاعة"),
                ),
                ("capacity_hall", models.IntegerField(verbose_name="سعة القاعة")),
            ],
            options={
                "verbose_name": "قاعة",
                "verbose_name_plural": "القاعات",
                "ordering": ["hall_name"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_name",
                    models.CharField(max_length=50, verbose_name="اسم المستوى"),
                ),
                ("number_students", models.IntegerField(verbose_name="عدد الطلاب")),
            ],
            options={
                "verbose_name": "مستوى",
                "verbose_name_plural": "المستويات",
                "ordering": ["fk_program__program_name", "level_name"],
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.IntegerField(
                        choices=[
                            (1, "8:00 - 10:00"),
                            (2, "10:00 - 12:00"),
                            (3, "12:00 - 2:00"),
                            (4, "2:00 - 4:00"),
                            (5, "4:00 - 6:00"),
                        ],
                        verbose_name="الفترة الزمنية",
                    ),
                ),
            ],
            options={
                "verbose_name": "فترة",
                "verbose_name_plural": "الفترات",
                "ordering": ["period"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program_name",
                    models.CharField(max_length=50, verbose_name="اسم البرنامج"),
                ),
            ],
            options={
                "verbose_name": "برنامج",
                "verbose_name_plural": "البرامج",
                "ordering": ["program_name"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
                ),
                (
                    "table",
                    models.FileField(
                        upload_to="tables_file/", verbose_name="ملف الجدول"
                    ),
                ),
            ],
            options={
                "verbose_name": "جدول",
                "verbose_name_plural": "الجداول",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_name",
                    models.CharField(max_length=50, verbose_name="اسم المدرس"),
                ),
                (
                    "teacher_address",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="عنوان المدرس",
                    ),
                ),
                (
                    "teacher_phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="هاتف المدرس"
                    ),
                ),
                (
                    "teacher_email",
                    models.EmailField(
                        max_length=100,
                        unique=True,
                        verbose_name="بريد المدرس الإلكتروني",
                    ),
                ),
            ],
            options={
                "verbose_name": "المدرس",
                "verbose_name_plural": "المدرسة",
                "ordering": ["teacher_name"],
            },
        ),
        migrations.CreateModel(
            name="Today",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_name",
                    models.CharField(
                        choices=[
                            ("sat", "السبت"),
                            ("sun", "الأحد"),
                            ("mon", "الاثنين"),
                            ("tue", "الثلاثاء"),
                            ("wed", "الأربعاء"),
                            ("thu", "الخميس"),
                            ("fri", "الجمعة"),
                        ],
                        max_length=10,
                        verbose_name="اسم اليوم",
                    ),
                ),
            ],
            options={
                "verbose_name": "يوم",
                "verbose_name_plural": "الأيام",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(max_length=50, verbose_name="اسم المجموعة"),
                ),
                ("number_students", models.IntegerField(verbose_name="عدد الطلاب")),
                (
                    "fk_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="timetable.level",
                        verbose_name="المستوى",
                    ),
                ),
            ],
            options={
                "verbose_name": "مجموعة",
                "verbose_name_plural": "المجموعات",
                "ordering": ["fk_level__level_name", "group_name"],
            },
        ),
        migrations.AddField(
            model_name="level",
            name="fk_program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levels",
                to="timetable.program",
                verbose_name="البرنامج",
            ),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(max_length=100, verbose_name="اسم المادة"),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "fk_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="timetable.level",
                        verbose_name="المستوى",
                    ),
                ),
            ],
            options={
                "verbose_name": "مادة",
                "verbose_name_plural": "المواد",
                "ordering": ["fk_level__level_name", "subject_name"],
            },
        ),
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="timetable.group",
                        verbose_name="المجموعة",
                    ),
                ),
                (
                    "fk_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="timetable.subject",
                        verbose_name="المادة",
                    ),
                ),
                (
                    "fk_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="timetable.teacher",
                        verbose_name="الأستاذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "توزيع",
                "verbose_name_plural": "التوزيعات",
                "ordering": ["fk_group__group_name", "fk_subject__subject_name"],
                "unique_together": {("fk_group", "fk_teacher", "fk_subject")},
            },
        ),
        migrations.CreateModel(
            name="TeacherTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_availability",
                        to="timetable.period",
                        verbose_name="الفترة",
                    ),
                ),
                (
                    "fk_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available_times",
                        to="timetable.teacher",
                        verbose_name="الأستاذ",
                    ),
                ),
                (
                    "fk_today",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_availability",
                        to="timetable.today",
                        verbose_name="اليوم",
                    ),
                ),
            ],
            options={
                "verbose_name": "وقت الأستاذ",
                "verbose_name_plural": "أوقات الأساتذة",
                "ordering": [
                    "fk_teacher__teacher_name",
                    "fk_today__id",
                    "fk_period__period",
                ],
                "unique_together": {("fk_teacher", "fk_today", "fk_period")},
            },
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to="timetable.distribution",
                        verbose_name="التوزيع",
                    ),
                ),
                (
                    "fk_hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to="timetable.hall",
                        verbose_name="القاعة",
                    ),
                ),
                (
                    "fk_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to="timetable.table",
                        verbose_name="الجدول",
                    ),
                ),
                (
                    "fk_teachertime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to="timetable.teachertime",
                        verbose_name="وقت الأستاذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "محاضرة",
                "verbose_name_plural": "المحاضرات",
                "ordering": [
                    "fk_table__created_at",
                    "fk_teachertime__fk_today__id",
                    "fk_teachertime__fk_period__period",
                ],
                "unique_together": {("fk_hall", "fk_teachertime", "fk_table")},
            },
        ),
    ]
