# Generated by Django 5.2.3 on 2025-07-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_name',
            field=models.CharField(choices=[('1-الأول', 'الأول'), ('2-الثاني', 'الثاني'), ('3-الثالث', 'الثالث'), ('4-الرابع', 'الرابع')], max_length=50, verbose_name='اسم المستوى'),
        ),
    ]
