# Generated by Django 4.2 on 2025-07-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
