# Generated by Django 5.2.3 on 2025-06-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="teacher_status",
            field=models.IntegerField(
                choices=[(1, "تشط"), (2, "اجازة")],
                default=1,
                verbose_name="حالة المدرس",
            ),
        ),
    ]
