# Generated by Django 5.2.3 on 2025-06-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0002_teacher_teacher_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="teacher_status",
            field=models.IntegerField(
                choices=[(1, "تشط"), (2, "اجازة")], verbose_name="حالة المدرس"
            ),
        ),
    ]
