# Generated by Django 5.2.3 on 2025-07-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_level_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_name',
            field=models.CharField(choices=[(1, 'الأول'), (2, 'الثاني'), (3, 'الثالث'), (4, 'الرابع')], max_length=50, verbose_name='اسم المستوى'),
        ),
    ]
