# Generated by Django 4.2 on 2025-07-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0002_alter_teacher_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="hall_status",
            field=models.CharField(
                choices=[("available", "متاحة"), ("under_maintenance", "تحت الصيانة")],
                default="available",
                max_length=20,
                verbose_name="حالة القاعة",
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="level_name",
            field=models.CharField(
                choices=[
                    ("first", "الأول"),
                    ("second", "الثاني"),
                    ("third", "الثالث"),
                    ("fourth", "الرابع"),
                ],
                max_length=50,
                verbose_name="اسم المستوى",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="term",
            field=models.CharField(
                choices=[("term1", "الأول"), ("term2", "الثاني")],
                default="term1",
                max_length=10,
                verbose_name="الفصل الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="teacher_status",
            field=models.CharField(
                choices=[("active", "نشط"), ("vacation", "إجازة")],
                default="active",
                max_length=100,
                verbose_name="حالة المدرس",
            ),
        ),
        migrations.AlterField(
            model_name="today",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
