# Generated by Django 4.2 on 2025-07-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0003_alter_hall_hall_status_alter_level_level_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="today",
            name="day_name",
            field=models.CharField(
                choices=[
                    ("0", "السبت"),
                    ("1", "الأحد"),
                    ("2", "الاثنين"),
                    ("3", "الثلاثاء"),
                    ("4", "الأربعاء"),
                    ("5", "الخميس"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
    ]
