# Generated by Django 5.2.3 on 2025-06-24 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0003_alter_teacher_teacher_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "ordering": ["teacher_name"],
                "verbose_name": "المدرس",
                "verbose_name_plural": "المدرسين",
            },
        ),
    ]
