# Generated by Django 5.2.3 on 2025-07-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_level_level_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'مستوى', 'verbose_name_plural': 'المستويات'},
        ),
    ]
