# Generated by Django 5.2.3 on 2025-06-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0004_alter_teacher_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="teacher_status",
            field=models.CharField(
                choices=[("نشط", "تشط"), ("اجازة", "اجازة")], verbose_name="حالة المدرس"
            ),
        ),
    ]
