# Generated by Django 5.2.3 on 2025-06-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0005_alter_teacher_teacher_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="teacher_status",
            field=models.CharField(
                choices=[("active", "نشط"), ("on_leave", "إجازة")],
                verbose_name="حالة المدرس",
            ),
        ),
    ]
