# Generated by Django 5.2.3 on 2025-07-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_level_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['fk_table__created_at', 'fk_teachertime__fk_today__id', 'fk_teachertime__fk_period__period_from'], 'verbose_name': 'محاضرة', 'verbose_name_plural': 'المحاضرات'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'فترة', 'verbose_name_plural': 'الفترات'},
        ),
        migrations.AlterModelOptions(
            name='teachertime',
            options={'ordering': ['fk_teacher__teacher_name', 'fk_today__id', 'fk_period__period_from'], 'verbose_name': 'وقت الأستاذ', 'verbose_name_plural': 'أوقات الأساتذة'},
        ),
        migrations.RemoveField(
            model_name='period',
            name='period',
        ),
        migrations.AddField(
            model_name='period',
            name='period_from',
            field=models.TimeField(default='08:00', help_text='مثال: 08:00', verbose_name='من الساعة'),
        ),
        migrations.AddField(
            model_name='period',
            name='period_to',
            field=models.TimeField(default='10:00', help_text='مثال: 10:00', verbose_name='إلى الساعة'),
        ),
    ]
