# Generated by Django 5.2.3 on 2025-06-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0006_alter_teacher_teacher_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="teacher_status",
            field=models.CharField(
                choices=[("نشط", "نشط"), ("إجازة", "إجازة")], verbose_name="حالة المدرس"
            ),
        ),
        migrations.AlterField(
            model_name="today",
            name="day_name",
            field=models.CharField(
                choices=[
                    ("1", "السبت"),
                    ("2", "الأحد"),
                    ("3", "الاثنين"),
                    ("4", "الثلاثاء"),
                    ("5", "الأربعاء"),
                    ("6", "الخميس"),
                    ("7", "الجمعة"),
                ],
                max_length=10,
                verbose_name="اسم اليوم",
            ),
        ),
    ]
