# Generated by Django 5.2.3 on 2025-07-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_lecture_options_alter_period_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['period_from'], 'verbose_name': 'فترة', 'verbose_name_plural': 'الفترات'},
        ),
        migrations.AlterField(
            model_name='period',
            name='period_from',
            field=models.TimeField(help_text='مثال: 08:00', verbose_name='من الساعة'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period_to',
            field=models.TimeField(help_text='مثال: 10:00', verbose_name='إلى الساعة'),
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('period_from', 'period_to')},
        ),
    ]
