# Generated by Django 5.2.3 on 2025-07-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_alter_period_options_alter_period_period_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='period_from',
            field=models.CharField(help_text='مثال: 08:00', verbose_name='من الساعة'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period_to',
            field=models.CharField(help_text='مثال: 10:00', verbose_name='إلى الساعة'),
        ),
    ]
