# Generated by Django 5.2.3 on 2025-06-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0007_alter_teacher_teacher_status_alter_today_day_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="term",
            field=models.CharField(
                default="الاول", max_length=50, verbose_name="الفصل الدراسي"
            ),
        ),
    ]
