# Generated by Django 5.2.3 on 2025-06-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0008_alter_subject_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="hall",
            name="hall_status",
            field=models.CharField(
                choices=[("متاح", "متاح"), ("تحت الصيانة", "تحت الصيانة")],
                default="متاح",
                verbose_name="حالة القاعة",
            ),
        ),
    ]
