# Generated by Django 5.2.3 on 2025-07-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_alter_period_period_from_alter_period_period_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['period_from', 'period_to'], 'verbose_name': 'فترة', 'verbose_name_plural': 'الفترات'},
        ),
    ]
