# Generated by Django 5.2.3 on 2025-06-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0009_hall_hall_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="hall_status",
            field=models.CharField(
                choices=[("متاحة", "متاحة"), ("تحت الصيانة", "تحت الصيانة")],
                default="متاح",
                verbose_name="حالة القاعة",
            ),
        ),
    ]
