# Generated by Django 5.2.3 on 2025-07-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_alter_period_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'فترة', 'verbose_name_plural': 'الفترات'},
        ),
    ]
