# Generated by Django 5.2.3 on 2025-06-29 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_program_fk_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='fk_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='timetable.department', verbose_name='القسم التابع له'),
        ),
    ]
