# Generated by Django 5.2.3 on 2025-07-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_alter_program_fk_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='term',
            field=models.CharField(choices=[('الأول', 'الأول'), ('الثاني', 'الثاني')], default='الأول', verbose_name='الفصل الدراسي'),
        ),
    ]
