# Generated by Django 5.2.3 on 2025-07-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_alter_subject_term'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_name'], 'verbose_name': 'مادة', 'verbose_name_plural': 'المواد'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='fk_level',
        ),
    ]
