# Generated by Django 5.2.3 on 2025-07-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_table_name_alter_group_number_students_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['capacity_hall'], 'verbose_name': 'قاعة', 'verbose_name_plural': 'القاعات'},
        ),
    ]
