# Generated by Django 4.2 on 2025-07-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0016_table_name_alter_group_number_students_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="hall_status",
            field=models.CharField(
                choices=[("متاحة", "متاحة"), ("تحت الصيانة", "تحت الصيانة")],
                default="متاحة",
                max_length=20,
                verbose_name="حالة القاعة",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="term",
            field=models.CharField(
                choices=[("الأول", "الأول"), ("الثاني", "الثاني")],
                default="الأول",
                max_length=10,
                verbose_name="الفصل الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="teacher_status",
            field=models.CharField(
                choices=[("نشط", "نشط"), ("إجازة", "إجازة")],
                max_length=100,
                verbose_name="حالة المدرس",
            ),
        ),
    ]
