# Generated by Django 5.2.3 on 2025-07-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_alter_hall_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['-capacity_hall'], 'verbose_name': 'قاعة', 'verbose_name_plural': 'القاعات'},
        ),
    ]
