# Generated by Django 4.2 on 2025-07-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0017_alter_hall_hall_status_alter_subject_term_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
