# Generated by Django 4.2 on 2025-07-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0018_alter_teacher_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="teacher_status",
            field=models.CharField(
                choices=[("نشط", "نشط"), ("إجازة", "إجازة")],
                default="نشط",
                max_length=100,
                verbose_name="حالة المدرس",
            ),
        ),
    ]
