# Generated by Django 5.2.3 on 2025-07-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0018_alter_hall_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_name',
            field=models.CharField(choices=[('الأول', 'الأول'), ('الثاني', 'الثاني'), ('الثالث', 'الثالث'), ('الرابع', 'الرابع')], max_length=50, verbose_name='اسم المستوى'),
        ),
    ]
