# Generated by Django 4.2 on 2025-07-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0019_alter_teacher_teacher_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
