# Generated by Django 4.2 on 2025-07-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0020_alter_subject_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lecture",
            options={
                "ordering": [
                    "fk_table__created_at",
                    "fk_teachertime__fk_today__id",
                    "fk_teachertime__fk_period__id",
                ],
                "verbose_name": "محاضرة",
                "verbose_name_plural": "المحاضرات",
            },
        ),
        migrations.AlterModelOptions(
            name="period",
            options={},
        ),
        migrations.AlterModelOptions(
            name="teachertime",
            options={
                "ordering": [
                    "fk_teacher__teacher_name",
                    "fk_today__id",
                    "fk_period__id",
                ],
                "verbose_name": "وقت الأستاذ",
                "verbose_name_plural": "أوقات الأساتذة",
            },
        ),
        migrations.AlterModelOptions(
            name="today",
            options={},
        ),
        migrations.RemoveField(
            model_name="period",
            name="period",
        ),
        migrations.AddField(
            model_name="period",
            name="period_from",
            field=models.IntegerField(null=True, verbose_name="من الساعة"),
        ),
        migrations.AddField(
            model_name="period",
            name="period_to",
            field=models.IntegerField(null=True, verbose_name="إلى الساعة"),
        ),
        migrations.AlterField(
            model_name="today",
            name="day_name",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="today",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
