# Generated by Django 4.2 on 2025-07-06 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0021_alter_lecture_options_alter_period_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="period",
            options={
                "ordering": ["id"],
                "verbose_name": "فترة",
                "verbose_name_plural": "الفترات",
            },
        ),
        migrations.AlterModelOptions(
            name="today",
            options={
                "ordering": ["id"],
                "verbose_name": "يوم",
                "verbose_name_plural": "الأيام",
            },
        ),
    ]
