# Generated by Django 4.2 on 2025-07-06 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0022_alter_period_options_alter_today_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="program",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="program",
            name="fk_department",
        ),
    ]
