# Generated by Django 4.2 on 2025-07-06 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0023_alter_program_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="level",
            name="number_students",
        ),
    ]
