# Generated by Django 4.2 on 2025-07-14 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0024_remove_level_number_students"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lecture",
            options={"verbose_name": "محاضرة", "verbose_name_plural": "المحاضرات"},
        ),
        migrations.AlterUniqueTogether(
            name="lecture",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="lecture",
            name="fk_day",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day_lectures",
                to="timetable.today",
                verbose_name="اليوم",
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="fk_period",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="period_lectures",
                to="timetable.period",
                verbose_name="الفترة",
            ),
        ),
        migrations.RemoveField(
            model_name="lecture",
            name="fk_teachertime",
        ),
    ]
